# vim:fileencoding=utf-8:foldmethod=marker

#: Fonts {{{


font_family      MesloLGS NF Refular
bold_font        MesloLGS NF Bold
italic_font      MesloLGS NF Italic
bold_italic_font MesloLGS NF Bold Italic


#: Font size (in pts)

font_size 14.0

# Windows
hide_window_decorations titlebar-only
window_padding_width 10

# macos specifics 
macos_option_as_alt left
map cmd+c           copy_to_clipboard
map cmd+v           paste_from_clipboard
map shift+insert    paste_from_clipboard
mouse_map ctrl+left press ungrabbed,grabbed mouse_click_url

# Windo settings
background_opacity 0.9


# BEGIN_KITTY_THEME
# Everforest Dark Soft
include current-theme.conf
# END_KITTY_THEME
