#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top \
                  height=38 \
                  blur_radius=30 \
                  color=$BAR_COLOR \
                  padding_left=8 \
                  padding_right=8

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=4
  padding_right=4
  icon.font="SF Pro:Semibold:15.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$CREAM
  label.color=$CREAM
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
  background.corner_radius=6
  background.height=26
  background.color=$PANEL_COLOR
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

# One quiet instrument cluster instead of four competing pills.
sketchybar --add bracket system_status cpu battery volume calendar \
           --set system_status background.drawing=on \
                               background.color=$PANEL_COLOR \
                               background.corner_radius=6 \
                               background.height=26 \
                               background.border_width=1 \
                               background.border_color=$BORDER_COLOR

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update

# Seed AeroSpace workspace state immediately after a bar restart.
if command -v aerospace >/dev/null 2>&1; then
  FOCUSED_WORKSPACE="$(aerospace list-workspaces --focused 2>/dev/null)"
  sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE="$FOCUSED_WORKSPACE"
fi
