#!/bin/bash

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=37 blur_radius=30 color=$TRANSPARENT

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=3
  padding_right=3
  icon.font="SF Pro:Semibold:15.0"
  label.font="Hack Nerd Font:Bold:14.0"
  icon.color=$WHITE
  label.color=$WHITE
  icon.padding_left=3
  icon.padding_right=3
  label.padding_left=4
  label.padding_right=4
  background.corner_radius=5
  background.height=24
  background.color=$BG_COLOR
)
sketchybar --default "${default[@]}"

# -- Left Side Items --
source $ITEM_DIR/spaces.sh
source $ITEM_DIR/front_app.sh

# -- Right Side Of Notch Items --
source $ITEM_DIR/media.sh

# --- Right Side Items ---
source $ITEM_DIR/calendar.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh


##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
